# Nixpacks Configuration for Railway
# Collectorium Django Project

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "gunicorn collectorium.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120"

[variables]
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "collectorium.settings.railway"
