services:
  # Django Web Service
  - type: web
    name: collectorium
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "bash ./build.sh"
    startCommand: "bash ./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: collectorium.settings.render
      - key: DATABASE_URL
        fromDatabase:
          name: collectorium-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@collectorium.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
    autoDeploy: true
    healthCheckPath: /healthz/

databases:
  # PostgreSQL Database
  - name: collectorium-db
    region: frankfurt
    plan: free
    databaseName: collectorium
    user: collectorium
