services:
  # Django Web Service
  - type: web
    name: collectorium
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput --clear"
    startCommand: "python manage.py migrate --noinput && gunicorn collectorium.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --threads 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: collectorium.settings.render
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@collectorium.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
    autoDeploy: true
    healthCheckPath: /healthz/

databases:
  # PostgreSQL Database
  - name: collectorium-db
    region: frankfurt
    plan: free
    databaseName: collectorium
    user: collectorium
